# SPDX-License-Identifier: GPL-2.0

undefine CFLAGS

# Makefiles suck: This macro sets a default value of $(2) for the
# variable named by $(1), unless the variable has been set by
# environment or command line. This is necessary for CC and AR
# because make sets default values, so the simpler ?= approach
# won't work as expected.
define allow-override
  $(if $(or $(findstring environment,$(origin $(1))),\
            $(findstring command line,$(origin $(1)))),,\
    $(eval $(1) = $(2)))
endef

$(call allow-override,MESON,meson)
$(call allow-override,MESON_BUILD_DIR,build)

include $(src)/scripts/utils.mk

LIBTRACEEVENT_SHARED_MESON = $(srctree)/build/src/libtraceevent.so
LIBTRACEEVENT_STATIC_MESON = $(srctree)/build/src/libtraceevent.a
TEMP_MESON = $(srctree)/build/src/.tmp.libtraceevent.a

all: $(LIBTRACEEVENT_STATIC_MESON) $(LIBTRACEEVENT_SHARED_MESON)

PHONY += compile
compile: $(MESON_BUILD_DIR) force
	$(MESON) compile -C $(MESON_BUILD_DIR)

$(LIBTRACEEVENT_SHARED_MESON): compile

$(LIBTRACEEVENT_STATIC_MESON): $(LIBTRACEEVENT_SHARED_MESON)
	$(Q)objcopy $(call redefine_local,$(LIBTRACEEVENT_SHARED_MESON)) $(LIBTRACEEVENT_STATIC_MESON) $(TEMP_MESON)
	mv $(TEMP_MESON) $(LIBTRACEEVENT_STATIC_MESON)

$(MESON_BUILD_DIR):
	$(MESON) setup --prefix=$(prefix) $(MESON_BUILD_DIR)

install: $(LIBTRACEEVENT_STATIC_MESON)
	$(MESON) install -C $(MESON_BUILD_DIR)

docs: $(MESON_BUILD_DIR)
	$(MESON) compile -C build docs

PHONY += clean_meson
clean_meson:
	$(Q)$(RM) -rf $(MESON_BUILD_DIR)

PHONY += force
force:
